---
title: "Day 3: Gear Ratios"
---
## Part 1
You and the Elf eventually reach a gondola lift station; he says the gondola lift will take you up to the water source, but this is as far as he can bring you. You go inside.

It doesn't take long to find the gondolas, but there seems to be a problem: they're not moving.

"Aaah!"

You turn around to see a slightly-greasy Elf with a wrench and a look of surprise. "Sorry, I wasn't expecting anyone! The gondola lift isn't working right now; it'll still be a while before I can fix it." You offer to help.

The engineer explains that an engine part seems to be missing from the engine, but nobody can figure out which one. If you can add up all the part numbers in the engine schematic, it should be easy to work out which part is missing.

The engine schematic (your puzzle input) consists of a visual representation of the engine. There are lots of numbers and symbols you don't really understand, but apparently any number adjacent to a symbol, even diagonally, is a "part number" and should be included in your sum. (Periods (.) do not count as a symbol.)

Here is an example engine schematic:

```
467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...$.*....
.664.598..
```
In this schematic, two numbers are not part numbers because they are not adjacent to a symbol: 114 (top right) and 58 (middle right). Every other number is adjacent to a symbol and so is a part number; their sum is 4361.

Of course, the actual engine schematic is much larger. What is the sum of all of the part numbers in the engine schematic?

```{python}
import re
from typing import List, Tuple, Set
from collections import namedtuple

example = """467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...$.*....
.664.598.."""

def check_line(before:str, current:str, after:str, SYMBOLS:Set[str]) -> int:
    valid_nums = []
    symbol_pos = {i for i,v in enumerate(before) if v in SYMBOLS}
    symbol_pos |= {i for i,v in enumerate(current) if v in SYMBOLS}
    symbol_pos |= {i for i,v in enumerate(after) if v in SYMBOLS}
    
    for r in re.finditer("[\d]+", current):
        num_pos = set(range(r.span()[0] - 1, r.span()[1] + 1))
        if symbol_pos & num_pos:
            valid_nums.append(int(r.group(0)))
    
    return sum(valid_nums)

def part1(inp:str) -> int:
    SYMBOLS = set(inp) - set('0123456789') - set('\n.')
    lines = inp.splitlines()
    lines.insert(0, "." * len(lines[0]))
    lines.append("." * len(lines[0])) 
    before = lines
    current = lines[1:-1]
    after = lines[2:]

    valid_nums = [check_line(*step, SYMBOLS) for step in zip(before, current, after)]

    return sum(valid_nums)

part1(example)
```

```{python}
with open("./input.txt") as f:
    inp = f.read()
part1(inp)
```

## Part 2

## TIL

### Using an expanded list and `zip` to extract moving window of current line, line before and line after

```{python}
data = example
SYMBOLS = set(data) - set('0123456789') - set('\n.')
SYMBOLS

lines = example.splitlines()
lines.insert(0, "." * len(lines[0]))
lines.append("." * len(lines[0]))

before = lines
current = lines[1:-1]
after = lines[2:]

for step in zip(before, current, after):
    print(*step)

```

### `|=` performs in-place OR operation for LHS and RHS
See [https://stackoverflow.com/questions/3929278/what-does-ior-do-in-python](https://stackoverflow.com/questions/3929278/what-does-ior-do-in-python) 

### `re.finditer()` finds both matching pattern and span
```{python}
for line in current:
    for r in re.finditer("\d+", line):
        print(r)
```